### PR TITLE
Fix NoMethodError when running with --no-xvfb flag

### LINKED ISSUE #49: Running with --no-xvfb flag causes NoMethodError
```bash
/rspec_starter-1.4.0/lib/rspec_starter/steps/prepare_database_step.rb:50:in `successful?': undefined method `exitstatus' for nil:NilClass (NoMethodError)
```
This is happening [here](https://github.com/roberts1000/rspec_starter/blob/master/lib/rspec_starter/steps/prepare_database_step.rb#L50) because running rspec_starter without xvfb causes $CHILD_STATUS to be nil.

### PR DESCRIPTION
**Pull request by coliver**
Fixes #49

### CODE REVIEW

**Comment by roberts1000** [comment]
I moved the method you fixed to [here](https://github.com/roberts1000/rspec_starter/blob/master/lib/rspec_starter/legacy/steps/prepare_database_step.rb).  I _think_ the issue is probably already fixed since I stopped querying `$CHILD_STATUS`, but double check me. If it's still broken, I'll pull in your PR.

**Comment by coliver** [comment]
> I moved the method you fixed to [here](https://github.com/roberts1000/rspec_starter/blob/master/lib/rspec_starter/legacy/steps/prepare_database_step.rb). I _think_ the issue is probably already fixed since I stopped querying `$CHILD_STATUS`, but double check me. If it's still broken, I'll pull in your PR.

Looking...

**Comment by coliver** [comment]
@roberts1000 Yeah, your change looks like it should fix it. I'll close this PR.

**Comment by roberts1000** [comment]
Thanks for confirming.

**Pull request closed without merging**
